package proxychecker

import (
	"net/http"
	"sync"
)

type Proxy struct {
    Address string
    Type    string
}

type ProxyChecker struct {
    Cache      []Proxy
    CacheLock  sync.Mutex
    Client     *http.Client
    Headers    map[string]string
    Proxies    sync.Map
    CheckLimit int
	ConcurrencyLimit int
}

var (
	httpServers = [13]string{
        "https://www.cloudflare.com/cdn-cgi/trace",
        "https://www.google.com",
        "https://www.youtube.com",
        "https://www.facebook.com",
        "https://www.amazon.com",
        "https://www.instagram.com",
        "https://www.whatsapp.com",
        "https://www.linkedin.com",
        "https://www.bing.com",
        "https://aws.amazon.com",
        "https://www.x.com",
        "https://www.alibaba.com",
        "https://www.apple.com",
    }
	urls = []string{
		"https://biskutliat.blogspot.com/",
		"https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks4&timeout=10000&country=all",
		"https://raw.githubusercontent.com/opsxcq/proxy-list/master/list.txt",
		"https://proxyfirenet.blogspot.com/",
		"https://raw.githubusercontent.com/prxchk/proxy-list/main/socks4.txt",
		"https://raw.githubusercontent.com/B4RC0DE-TM/proxy-list/main/SOCKS5.txt",
		"https://api.proxyscrape.com/v2/?request=getproxies&protocol=http&timeout=10000&country=all&ssl=all&anonymity=all",
		"https://api.openproxylist.xyz/http.txt",
		"https://raw.githubusercontent.com/proxifly/free-proxy-list/main/proxies/all/data.txt",
		"https://www.proxy-list.download/api/v1/get?type=https",
		"https://api.proxyscrape.com/?request=getproxies&proxytype=https&timeout=10000&country=all&ssl=all&anonymity=all",
		"https://raw.githubusercontent.com/casals-ar/proxy-list/main/socks4",
		"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks4.txt",
		"https://vipprox.blogspot.com/2013/05/us-proxy-servers-74_24.html",
		"https://atomintersoft.com/proxy_list_domain_net",
		"https://raw.githubusercontent.com/manuGMG/proxy-365/main/SOCKS5.txt",
		"https://raw.githubusercontent.com/a2u/free-proxy-list/master/free-proxy-list.txt",
		"https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list-raw.txt",
		"https://browse.feedreader.com/c/Proxy_Server_List-1/449196258",
		"https://raw.githubusercontent.com/ALIILAPRO/Proxy/main/socks5.txt",
		"https://raw.githubusercontent.com/officialputuid/KangProxy/KangProxy/https/https.txt",
		"https://vipprox.blogspot.com/2013_06_01_archive.html",
		"https://free-ssh.blogspot.com/feeds/posts/default",
		"https://www.proxy-list.download/api/v1/get?type=socks4",
		"https://atomintersoft.com/proxy_list_port_80",
		"https://www.socks-proxy.net/",
		"https://openproxy.space/list/socks5",
		"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt",
		"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt",
		"https://raw.githubusercontent.com/B4RC0DE-TM/proxy-list/main/SOCKS4.txt",
		"https://atomintersoft.com/high_anonymity_elite_proxy_list",
		"https://raw.githubusercontent.com/rdavydov/proxy-list/main/proxies_anonymous/socks5.txt",
		"https://proxyspace.pro/socks5.txt",
		"https://raw.githubusercontent.com/MuRongPIG/Proxy-Master/main/socks5.txt",
		"https://johnstudio0.tripod.com/index1.htm",
		"https://raw.githubusercontent.com/saisuiu/Lionkings-Http-Proxys-Proxies/main/cnfree.txt",
		"https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks5&timeout=10000&country=all",
		"https://atomintersoft.com/proxy_list_domain_org",
		"https://api.proxyscrape.com/v2/?request=displayproxies&protocol=socks4",
		"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies_anonymous/http.txt",
		"https://vipprox.blogspot.com/2013/05/us-proxy-servers-199_20.html",
		"https://free-proxy-list.net/",
		"https://browse.feedreader.com/c/Proxy_Server_List-1/449196259",
		"https://raw.githubusercontent.com/zevtyardt/proxy-list/main/http.txt",
		"https://sockproxy.blogspot.com/2013/04/11-04-13-socks-45.html",
		"https://raw.githubusercontent.com/prxchk/proxy-list/main/socks5.txt",
		"https://www.javatpoint.com/proxy-server-list",
		"https://raw.githubusercontent.com/sunny9577/proxy-scraper/master/generated/socks5_proxies.txt",
		"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt",
		"https://atomintersoft.com/products/alive-proxy/proxy-list/com",
		"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies_anonymous/socks4.txt",
		"https://proxyspace.pro/https.txt",
		"https://www.cybersyndrome.net/plr5.html",
		"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks4.txt",
		"https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt",
		"https://raw.githubusercontent.com/proxy4parsing/proxy-list/main/http.txt",
		"https://sunny9577.github.io/proxy-scraper/proxies.txt",
		"https://openproxy.space/list/http",
		"https://api.proxyscrape.com/?request=getproxies&proxytype=socks5&timeout=10000&country=all",
		"https://proxy-list.org/english/index.php",
		"https://api.proxyscrape.com/?request=displayproxies&proxytype=socks4&country=all",
		"https://raw.githubusercontent.com/rdavydov/proxy-list/main/proxies/socks4.txt",
		"https://atomintersoft.com/anonymous_proxy_list",
		"https://raw.githubusercontent.com/zloi-user/hideip.me/main/http.txt",
		"https://globalproxies.blogspot.com/",
		"https://raw.githubusercontent.com/zloi-user/hideip.me/main/socks4.txt",
		"https://vpnoverview.com/privacy/anonymous-browsing/free-proxy-servers/",
		"https://raw.githubusercontent.com/prxchk/proxy-list/main/http.txt",
		"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks5.txt",
		"https://raw.githubusercontent.com/MuRongPIG/Proxy-Master/main/socks4.txt",
		"https://api.proxyscrape.com/?request=getproxies&proxytype=socks4&timeout=10000&country=all",
		"https://proxyspace.pro/socks4.txt",
		"https://raw.githubusercontent.com/zloi-user/hideip.me/main/https.txt",
		"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt",
		"https://pastebin.com/raw/qUNWyhbE",
		"https://multiproxy.org/txt_all/proxy.txt",
		"https://atomintersoft.com/products/alive-proxy/socks5-list",
		"https://alexa.lr2b.com/proxylist.txt",
		"https://atomintersoft.com/transparent_proxy_list",
		"https://raw.githubusercontent.com/shiftytr/proxy-list/master/proxy.txt",
		"https://raw.githubusercontent.com/officialputuid/KangProxy/KangProxy/http/http.txt",
		"https://free-proxy-list.com/",
		"https://www.cybersyndrome.net/pla5.html",
		"https://www.cybersyndrome.net/plz.html",
		"https://www.proxy-list.download/api/v1/get?type=socks5",
		"https://atomintersoft.com/proxy_list_port_81",
		"https://raw.githubusercontent.com/MuRongPIG/Proxy-Master/main/http.txt",
		"https://raw.githubusercontent.com/ALIILAPRO/Proxy/main/socks4.txt",
		"https://raw.githubusercontent.com/roosterkid/openproxylist/main/HTTPS_RAW.txt",
		"https://rootjazz.com/proxies/proxies.txt",
		"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-https.txt",
		"https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/https.txt",
		"https://www.us-proxy.org/",
		"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks5.txt",
		"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/https.txt",
		"https://raw.githubusercontent.com/rdavydov/proxy-list/main/proxies_anonymous/socks4.txt",
		"https://hidemy.io/en/proxy-list/",
		"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/proxy.txt",
		"https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS4_RAW.txt",
		"https://www.sslproxies.org/",
		"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt",
		"https://www.proxy-list.download/api/v1/get?type=http",
		"https://raw.githubusercontent.com/zevtyardt/proxy-list/main/socks4.txt",
		"https://api.proxyscrape.com/v2/?request=displayproxies&protocol=socks5",
		"https://raw.githubusercontent.com/casals-ar/proxy-list/main/https",
		"https://freeproxylist-daily.blogspot.com/2013/05/usa-proxy-list-2013-05-13-812-gmt7.html",
		"https://www.proxynova.com/proxy-server-list/",
		"https://browse.feedreader.com/c/Proxy_Server_List-1/449196251",
		"https://atomintersoft.com/products/alive-proxy/proxy-list/3128",
		"https://sock5us.blogspot.com/2013/06/01-07-13-free-proxy-server-list.html#comment-form",
		"https://raw.githubusercontent.com/rdavydov/proxy-list/main/proxies_anonymous/http.txt",
		"https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/socks5.txt",
		"https://hidemy.name/en/proxy-list/",
		"https://atomintersoft.com/products/alive-proxy/proxy-list/high-anonymity/",
		"https://pastebin.com/raw/VJwVkqRT",
		"https://raw.githubusercontent.com/sunny9577/proxy-scraper/master/generated/socks4_proxies.txt",
		"https://raw.githubusercontent.com/mmpx12/proxy-list/master/http.txt",
		"https://raw.githubusercontent.com/mmpx12/proxy-list/master/socks4.txt",
		"https://raw.githubusercontent.com/zevtyardt/proxy-list/main/socks5.txt",
		"https://atomintersoft.com/proxy_list_port_8000",
		"https://spys.one/",
		"https://vipprox.blogspot.com/p/blog-page_7.html",
		"https://raw.githubusercontent.com/zloi-user/hideip.me/main/socks5.txt",
		"https://raw.githubusercontent.com/mmpx12/proxy-list/master/socks5.txt",
		"https://vipprox.blogspot.com/2013_03_01_archive.html",
		"https://raw.githubusercontent.com/sunny9577/proxy-scraper/master/proxies.txt",
		"https://raw.githubusercontent.com/rdavydov/proxy-list/main/proxies/socks5.txt",
		"https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS5_RAW.txt",
		"https://raw.githubusercontent.com/sunny9577/proxy-scraper/master/generated/http_proxies.txt",
		"https://vipprox.blogspot.com/2013_02_01_archive.html",
		"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies_anonymous/socks5.txt",
		"https://proxydb.net/",
		"https://freeproxylist-daily.blogspot.com/2013/05/usa-proxy-list-2013-05-15-0111-am-gmt8.html",
		"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks4.txt",
		"https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/socks4.txt",
		"https://api.openproxylist.xyz/socks4.txt",
		"https://api.proxyscrape.com/?request=getproxies&proxytype=http&timeout=10000&country=all&ssl=all&anonymity=all",
		"https://atomintersoft.com/proxy_list_domain_edu",
		"https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/http.txt",
		"https://raw.githubusercontent.com/casals-ar/proxy-list/main/http",
		"https://raw.githubusercontent.com/casals-ar/proxy-list/main/socks5",
		"https://atomintersoft.com/proxy_list_port_3128",
		"https://openproxy.space/list/socks4",
		"https://raw.githubusercontent.com/ALIILAPRO/Proxy/main/http.txt",
		"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks5.txt",
		"https://browse.feedreader.com/c/Proxy_Server_List-1/449196260",
		"https://raw.githubusercontent.com/rdavydov/proxy-list/main/proxies/http.txt",
		"https://api.proxyscrape.com/proxytable.php?nf=true&country=all",
		"https://atomintersoft.com/proxy_list_domain_com",
		"https://proxyspace.pro/http.txt",
		"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks4.txt",
		"https://raw.githubusercontent.com/Anonym0usWork1221/Free-Proxies/main/proxy_files/https_proxies.txt",
		"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies.txt",
		"https://raw.githubusercontent.com/B4RC0DE-TM/proxy-list/main/HTTP.txt",
		"https://api.proxyscrape.com/?request=displayproxies&proxytype=socks5",
		"https://raw.githubusercontent.com/Anonym0usWork1221/Free-Proxies/main/proxy_files/http_proxies.txt",
		"https://api.openproxylist.xyz/socks5.txt",
	}
	headers = map[string]string{
        "User-Agent":      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3",
        "Accept":          "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.5",
    }
	proxyTypes = []string{"http", "socks4", "socks5"}
)